[V3] Migrate `FileSystem` to use Rust's `std::fs` interface
atlassian-labs/atlaspack pull request #50
Opened 2024-08-30 06:54 UTC by alshdavid

This PR migrates the `FileSystem` implementation to adhere to the interface of the Rust standard library's fs api.

I started on this because I needed access to the `std::fs::read` function - but figured, rather than adding my own version of that function to the `FileSystem`, it would be better to tidy the `FileSystem` crate up before it deviates too far.

So this PR allows us to use methods that exist in the Rust standard library within the native code. Only the function we use have been implemented, we can expand them as needed in future.

This did require a bit of refactoring because we relied on some behaviours that were different to the std lib

2024-08-30 07:07 UTC, alshdavid commented on crates/atlaspack/src/requests/entry_request.rs
> -    if request_context.file_system().is_file(&entry_path) {
`is_file` would return `false` if the file did not exist. Some other circuits relied on this - is that required in this case?

2024-08-30 07:14 UTC, alshdavid commented on crates/atlaspack_filesystem/src/lib.rs
> -    _cache: &FileSystemRealPathCache,
I moved the cache implementation within the struct to function as an inner detail. We weren't sharing the cache around, just newing it up and passing it back into the fs.

```rust
let fs = OsFileSystem {
  cache: FileSystemRealPathCache::default()
}

fs.read(Path::from("/foo/bar.txt"))
```

2024-09-01 21:56 UTC, alshdavid commented on crates/atlaspack_config/src/atlaspack_rc_config_loader.rs
> -    self.fs.canonicalize_base(&path).map_err(|source| {
is `canonicalize_base` supposed to behave differently to `std::fs::canonicalize`? Should it be part of `FileSystemExt`?

2024-09-01 21:58 UTC, alshdavid commented on crates/atlaspack_filesystem/Cargo.toml
> -mockall = "0.12.1"
Removed `automock` because it has issues with the trait and we were not using it, all tests were using the `InMemoryFileSystem`

2024-09-01 21:58 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +  // -----------------------------------
TODO: Move the additional methods to a `FileSystemExt` trait

2024-09-01 21:59 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +    Ok(Box::new(Cursor::new(self.read(path)?)))
TODO; write support for `fs::open`. This isn't being used atm so I will finish it when it's needed

2024-09-01 22:01 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +impl std::fmt::Debug for InMemoryFileSystem {
This prints out the structure of the `InMemoryFilesystem` when passed into `dbg!(&fs)`. The content of the files is replaced with their size rather than printing their contents.

2024-09-01 22:02 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +  File { contents: Vec<u8> },
This was changed from an `String` to a `Vec<u8>` because Atlaspack can work with non text files - like images. This is needed for plugin support

2024-09-01 22:03 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/metadata.rs
https://doc.rust-lang.org/std/fs/struct.Metadata.html

2024-09-01 22:04 UTC, alshdavid commented on crates/atlaspack_filesystem/src/lib.rs
Making the library entry file function as only an index of the public exports

2024-09-01 22:07 UTC, alshdavid commented on crates/atlaspack_filesystem/src/os/canonicalize.rs
This can probably be generalized on top of the `FileSystem` trait rather than being fs-specific

2024-09-01 22:08 UTC, alshdavid commented on crates/atlaspack_filesystem/src/utils/find_ancestor.rs
TODO: Make this part of the `FileSystemExt` trait

2024-09-01 22:09 UTC, alshdavid commented on crates/atlaspack_napi_helpers/src/js_callable/js_callable.rs
Could probably just use `Arc<JsCallable>` at the call site :thinking:

2024-09-01 22:10 UTC, alshdavid commented on crates/node-bindings/src/file_system/file_system_napi.rs
TODO: Add tests for the Napi filesystem

2024-09-01 22:11 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +  // ------------------------
https://doc.rust-lang.org/std/fs/index.html

2024-09-01 22:11 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +
https://doc.rust-lang.org/std/fs/struct.Metadata.html

2024-09-01 22:12 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +
https://doc.rust-lang.org/std/fs/struct.Permissions.html

2024-09-01 22:12 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +
https://doc.rust-lang.org/std/fs/struct.FileType.html

2024-09-01 22:13 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +  }
Question: Why is `cwd` part of the filesystem? That's more of an environment thing

2024-09-01 22:15 UTC, alshdavid commented on crates/node-bindings/src/resolver.rs
TODO: Should probably move `JsFileSystem` into the `atlaspack_filesystem` crate and share the implementation with `resolver_old`

2024-09-01 22:17 UTC, alshdavid commented on packages/utils/node-resolver-rs/benches/node_resolver_bench.rs
TODO: Should move `PreloadingFileSystem` into the `atlaspack_filesystem` crate

2024-09-01 23:40 UTC, mattcompiles commented on crates/atlaspack_filesystem/src/file_system.rs
> +  fn hard_link(&self, _original: &Path, _link: &Path) -> io::Result<()> {
Why are implementing the entire FS API? Wouldn't it be easier to just leave out the ones we don't use?

2024-09-01 23:48 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +  fn hard_link(&self, _original: &Path, _link: &Path) -> io::Result<()> {
The trait simply documents the methods but they all default to `unimplemented!()`. The full fs methods are listed to avoid misnaming methods in future, ensuring correctness moving forward.

The `OsFileSystem` is the only implementation that implements all of the methods and only because it's effortless to forward the calls. Given all the tests use the `InMemoryFileSystem`, that's the real target for implementation and method implementations should be added there as needed.

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_config/src/atlaspack_rc_config_loader.rs
> -    self.fs.canonicalize_base(&path).map_err(|source| {
The `OsFileSystem` canonicalize implementation is different to std::fs::canonicalize and going through some caches. 

I reckon it does make some diff. to performance. The caching side of things should be moved out of the file-system trait.

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_filesystem/src/file_system.rs
> +    unimplemented!()
Remove all unimplemented defaults.

If we have it on the trait, implement for all file-system implementations. If we do not need it, then do not add to the trait.

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_filesystem/src/file_system.rs
> +  }
I think we need to set cwd / check cwd on some places no? Definitely for in-memory

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_filesystem/src/file_system.rs
> +
Do we really need a trait for this? Is there usage?

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +    Ok(Box::new(Cursor::new(self.read(path)?)))
I think we shouldn't support abstract file handles because that gets very complicated.

If we need to stream file contents, then let's just return readers / streams.

What are you using raw handles for?

2024-09-01 23:51 UTC, yamadapc commented on crates/atlaspack_filesystem/src/lib.rs
> -    _cache: &FileSystemRealPathCache,
Nice that's good

2024-09-01 23:55 UTC, alshdavid commented on crates/atlaspack_config/src/atlaspack_rc_config_loader.rs
> -    self.fs.canonicalize_base(&path).map_err(|source| {
Is the output different? Or does it produce the same output, the difference is that it uses a cache internally?

2024-09-01 23:58 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +    Ok(Box::new(Cursor::new(self.read(path)?)))
It's part of the plugin API to access/modify files via a reader/writer. Here, `File` is just an `io::Reader + io::Writer`.

It does add complexity though and I am ignoring that for now and will load & pass the entire file contents to consumers, just wrapping them to be readable

2024-09-02 00:02 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +  }
I'm more questioning if this is the right place for it.

Considering the FileSystem is just a map of filepaths -> contents, it has no concept of the current position of the user so it feels weird that it's a property of the filesystem itself.

Surely the user tracks their own cwd?

2024-09-02 00:04 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +
There is usage in the form of `FileSystemExt.exists()`, which must built on top of `FileType`

2024-09-02 00:12 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +    unimplemented!()
I placed all of the `std::fs` methods in the trait to ensure we do not add custom methods in future (or if we do, they get added to `FileSystemExt`).

They are unimplemented by default because it gives us visibility of the fs methods during development (intellisense), and when failures occur at runtime, we are prompted to satisfy the implementations.  

`OsFileSystem` forwards all the `FileSystem` methods to `std::fs` because that's easy to do. `InMemoryFileSystem`, implements them as-required because that's harder.

Lastly, minor point but, having all of the methods allows the `atlaspack_filesystem` crate to be used by plugin developers and other Rust projects within Atlassian, helping with the interoperability of Atlaspack.

2024-09-02 00:23 UTC, yamadapc commented on crates/atlaspack_config/src/atlaspack_rc_config_loader.rs
> -    self.fs.canonicalize_base(&path).map_err(|source| {
It should have the same output 🤞, but it's trying to minimize nº of syscalls (should have less `realpath` calls once the caches are populated). Whereas `std::fs::canonicalize` is just `libc::realpath`.

2024-09-02 00:25 UTC, yamadapc commented on packages/utils/node-resolver-rs/benches/node_resolver_bench.rs
This is just example code

2024-09-02 00:27 UTC, yamadapc requested changes
Please remove methods we aren't using or that aren't implemented for all back-ends.

2024-09-02 00:28 UTC, alshdavid commented on crates/atlaspack_config/src/atlaspack_rc_config_loader.rs
> -    self.fs.canonicalize_base(&path).map_err(|source| {
If it has the same signature, even if the implementation uses a cache internally, I feel it should not have it's own method.

Unless you're advocating for adding something like `FileSystemExt.canonicalize_cached()`? Or perhaps a `CachedFileSystem` that wraps `FileSystem` and can be applied to all of the fs implementations?

2024-09-02 00:32 UTC, alshdavid commented
> Please remove methods we aren't using or that aren't implemented for all back-ends.

I disagree with this request for the reasons stated in this [reply](https://github.com/atlassian-labs/atlaspack/pull/50#discussion_r1740222101). Can you please elaborate on why my points are invalid in this case?

2024-09-02 00:34 UTC, mattcompiles commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +    Ok(Box::new(Cursor::new(self.read(path)?)))
Where do we use this in a plugin that we need to support thought? Just cos you can do it today doesn't mean we should just blindly support it.

2024-09-02 00:41 UTC, alshdavid commented on crates/atlaspack_filesystem/src/in_memory/file_system.rs
> +    Ok(Box::new(Cursor::new(self.read(path)?)))
I'm not adding it into plugins atm, this is just here for completeness and for future reference.

Plugins will get the complete binary contents of their target file and `Asset.getStream()` will just return a `Reader` that reads over the entire blob

2024-09-02 00:41 UTC, yamadapc commented
There's no benefit in supporting intellisense to functions that are unimplemented and will lead to crashes at runtime.

Please either:

* implement the functions for all back-ends
* remove functions that we aren't using

2024-09-02 01:50 UTC, MonicaOlejniczak commented on crates/atlaspack_filesystem/src/utils/mod.rs
> +mod find_ancestor;
Can you revert this? `utils` is not as descriptive as `search` and sucks as a name

2024-09-02 01:53 UTC, MonicaOlejniczak commented on crates/atlaspack_filesystem/src/file_system.rs
> +  }
It's mostly for convenience, and because the original node filesystem contains cwd

2024-09-02 01:57 UTC, MonicaOlejniczak commented on crates/atlaspack_filesystem/src/file_system.rs
> +    unimplemented!()
Personally I don't think we need to create a filesystem implementation that matches the built-in rust impl 1:1. It's meant to be an atlaspack filesystem, so we should put things in the trait that make sense to be in there.

2024-09-02 02:00 UTC, MonicaOlejniczak commented on crates/atlaspack_filesystem/src/in_memory/canonicalize.rs
> +pub fn canonicalize_impl(current_working_directory: &RwLock<PathBuf>, path: &Path) -> PathBuf {
I would remove `_impl`, it's a standalone function

2024-09-02 02:05 UTC, alshdavid commented on crates/atlaspack_filesystem/src/file_system.rs
> +    unimplemented!()
My thinking is that, assuming we are expecting to migrate a bunch of plugins to native, we'd expect some external contributions. 

Having a filesystem interface that aligns with the standard library reduces friction during development for those contributors - plus IMO it's easier to just do what the standard lib does rather than inventing our own call signatures.

2024-09-02 04:09 UTC, MonicaOlejniczak commented on crates/atlaspack_filesystem/src/lib.rs
> -    _cache: &FileSystemRealPathCache,
Where will the boundary be for the cache? My concern is that it's unclear when the cache will be used and for which methods on the file system

2024-09-02 07:05 UTC, closed without merging